---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
library(tidyverse)
library(here)
library(naniar)
library(janitor)
```

```{r}
heartrate <- read_csv("data/heartrate.csv")
```
```{r}
glimpse(heartrate)
```

```{r}
heartrate
```


1. Make a plot that compares the heartrate of patients for drug a.

```{r}
heartrate %>%
  ggplot(aes(x=patient, y=a, fill=patient)) + geom_col() + 
  labs(title = "Comparison of Drug A induced Heartrate per Patient",
       x = "Patient",
       y = "Heartrate")
```


2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate %>%
  pivot_longer(-patient, 
               names_to = "drug_type", 
               values_to = "heartrate") %>%
  ggplot(aes(x=drug_type, y=heartrate, fill=drug_type)) + 
  geom_boxplot(alpha=.7) +
  labs(title = "Range of Heartrates per Drug Type",
       x = "Drug Type",
       y = "Heartrate")
```




